version: '2.1'

services:
  mongo:
    image: mongo
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      dockerfile: ./src/main/docker/Dockerfile
    environment:
      - SERVER_PORT=8080
      - MONGO_DB_CONNECTION_STRING=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE_NAME=Products
    ports:
      - "8080:8080"
    depends_on:
      - mongo


